name: 'dev workflow'

permissions:
  id-token: write
  contents: read

on:
 pull_request:
  branches:
   - main

 push:
   branches:
     - main
   
jobs:
  first-job:
    runs-on: self-hosted
    steps: 
    - name: checkout
      uses: actions/checkout@v5.0.0
      
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.11.0

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
       client-id: a277420d-f039-4b96-92d7-6a6a7bb1987b
       tenant-id: 6959824b-72a3-448d-9d04-fffb6db34d48
       subscription-id: 96a3eaff-d4cf-4222-9fe7-1622ab46f13e


      
      
               
