name: 'dev workflow'

permissions:
  id-token: write
  contents: read

on:
 pull_request:
  branches:
   - main

 push:
   branches:
     - main
   
jobs:
   terraform-init-plan:
    name: first job
    runs-on: [self-hosted, anjali]
    steps:
    - name: jaa login kr Azure se 
      uses: Azure/login@v2.3.0
      with:   
          client-id: 797b2efe-6a48-4c3b-b1b1-71b08221e046
          tenant-id: ee2f7139-4072-4385-99fc-82bd6f563aa6
          subscription-id: 98b7163f-e961-4b65-98c2-7a6dc2edf5b7

    - name: copy kr repo to self hosted runner me
      uses: actions/checkout@v4
      
    - name: Terraform Init chala
      id: init
      run: terraform init -input=false
      working-directory: environment/dev

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      working-directory: environment/dev
      
    - name: Terraform validate kr
      id: validate
      run: terraform validate
      working-directory: environment/dev 
      
    - name: Terraform Plan kr
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: environment/dev
      
   terraform-apply:
    name: second job
    runs-on: [self-hosted, anjali]
    needs: terraform-init-plan
    environment: dev
    # when you have ur main branch
    if: github.ref == 'refs/heads/main'
    steps:
    
      - name: Terraform Init chala
        id: init
        run: terraform init -input=false
        working-directory: environment/dev
        
      - name: Terraform apply kr
        id: apply
        run: terraform apply -auto-approve
        working-directory: environment/dev
        
