name: 'github action ka workflow'

on: workflow_dispatch

jobs:
  terraform-job:
    runs-on: self-hosted
    steps: 
    # checkout-------------------------------- task 1
    - name: checkout
      uses: actions/checkout@v5.0.0
    - name: Install Terraform
      # You may pin to the exact commit or the version.
      # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        # Version of terraform to download
        version: 1.12.0
              
    
    # # azure login
    # - name: Azure Login
    #   uses: Azure/login@v2.3.0
    #   with:
    #     # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
    #     creds: |
    #       {
    #         "appId": "48d50f0b-f076-432e-8b9c-e3e06d4d7a5e",
    #         "displayName": "azure-cli-2025-08-30-19-16-03",
    #         "password": "VUd8Q~p9y6EhluMAq0.5Rj~f-gYB~dMD_96dCbxZ",
    #         "tenant": "6959824b-72a3-448d-9d04-fffb6db34d48"
    #       }
    #     # ClientId of the Azure Service principal created.
    #     client-id: 'a277420d-f039-4b96-92d7-6a6a7bb1987b'
    # - name: Terraform init azurerm backend
    #   # You may pin to the exact commit or the version.
    #   # uses: ahmedig/terraform-azurerm-backend@65ed9d7f67790281b78670b7811d63d96f5e22ec
    #   uses: ahmedig/terraform-azurerm-backend@v4
    #   with:
    #     # Azure Credentials in JSON format
     
    #     azure_credentials: |
    #       {
    #         "client_id": "a277420d-f039-4b96-92d7-6a6a7bb1987b",
    #         "client_secret": "AEL8Q~Dke2iKOrvBod-5dzX.x9PYOc5PjdHFDcDg",
    #         "tenant_id": "6959824b-72a3-448d-9d04-fffb6db34d48",
    #         "subscription_id": "96a3eaff-d4cf-4222-9fe7-1622ab46f13e"
    #       }

    #     # State file location - resource group name
    #     resource_group_name: 'anjali-rg'
    #     # State file location - container name
    #     container_name: 'anji-con'
    #     # State file location - storage account name
    #     storage_account_name: 'anjalistorage12'
    #     # State file location - file name
    #     file_name: workflow.tfstate
    #     # Subscription Id of the resource group
    #     subscription_id: '96a3eaff-d4cf-4222-9fe7-1622ab46f13e'
    #     # Terraform working directory
    #     tf_working_directory: 'C:\actions-runner\_work\terraform-todoapp-infra\terraform-todoapp-infra\environment\dev'
              
         
    #         tenant-id: '6959824b-72a3-448d-9d04-fffb6db34d48'
    #         # Azure subscriptionId
    #         subscription-id: "96a3eaff-d4cf-4222-9fe7-1622ab46f13e"
    #         #
