name: 'github action ka workflow'

on: workflow_dispatch

jobs:
  terraform-job:
    runs-on: self-hosted
    steps: 
    # checkout-------------------------------- task 1
    - name: checkout
      uses: action/checkout@v5.0.0

